### ISSUE TITLE
Make available as npm package

### ISSUE THREAD

**Issue by brianmcmichael** [makerdao/dss-interfaces#8]
Package this up as an NPM package so that 3rd party developers can easily integrate with truffle and other popular tools.

**Comment by albertocuestacanada** [comment]
Here it is: https://www.npmjs.com/package/dss-interfaces

I'd like to hand it over to one of you for maintenance, does anyone in Maker have an npmjs account?

**Comment by brianmcmichael** [comment]
Done at https://github.com/makerdao/dss-interfaces/pull/46

Thank you!
